### ISSUE TITLE
Device module should use elixir/erlang convention for errors.

### ISSUE THREAD

**Issue by vic** [attm2x/m2x-elixir#7]
Hi,

I was using your library for setting up a little project at an att hackathon, and found that most of `Device` methods return `false` when request parameters are invalid (or anything bad happens on att servers).

Here is a sample of such a method...

https://github.com/attm2x/m2x-elixir/blob/master/lib/m2x/device.ex#L38

As far as I see most of the device methods perform the same idiom 

```elixir
res.success? and Enum.map(results ....)
```

causing the method to just return `false` instead of providing more useful information on why the request failed.

IMHO all these functions should follow the `{:ok, value}`  / `{:error, cause}` erlang/elixir idiom to allow
developers obtain more information about the failure.

I'd be interested in fixing this if you like, but just wanted to ask first as this might include several changes across all the m2x-elixir library.

Thoughts?

**Comment by jemc** [comment]
@vic You make a great point - I think this should be changed throughout the library (and perhaps in [m2x-erlang](https://github.com/attm2x/m2x-erlang) as well).

I've actually admired your work on [typhon](https://github.com/vic/typhon) in the past, so I definitely trust you to make the change if that's something you want to tackle!

Please feel free to comment and/or collaborate on any other usability issues you may run into - I'm glad the hackathon-goers are putting the library through its paces :wink:.

When we've finished, we can update a major version number for the next release, as semver dictates for breaking changes.

**Comment by jemc** [comment]
Hey @vic.

Just checking to see if you're still interested in implementing this?

Otherwise, I'm happy to tackle it myself.
